name: Google Books Frontend CI
on:
  push:
    branches: ["Main"]
  pull_request:
    branches: ["Main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node20
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
